architect:
   - serranya
assets:
   id_ed25519: serranya/priv-assets#id_ed25519
   id_ed25519.pub: serranya/priv-assets#id_ed25519.pub
   settings.xml: serranya/priv-assets#settings.xml
docker:
   image: "openjdk:11.0.4-jdk"
merge:
   - "./mvnw -B clean verify -Prelease"
release:
   script: |-
      mkdir -p ~/.ssh
      mv ../id_ed25519 ../id_ed25519.pub ~/.ssh
      chmod -R 600 ~/.ssh/*
      echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config
      git config --global user.email me@rultor.com
      git config --global user.name rultor
      ./mvnw -B -e --no-transfer-progress -s ../settings.xml clean deploy site-deploy -Drevision=$tag -Prelease

